name: deploy to lambda
on: [push]
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v1
      - name: Yarn Install On __video-maker-lambda
        uses: Borales/actions-yarn@v2.3.0
        with: 
            cmd: --cwd __video-maker-lambda
      - name: Zipping __video-maker-lambda
        uses: montudor/action-zip@v0.1.0
        with:
          args: cd __video-maker-lambda && zip -qq -r ../__video-maker-lambda.zip .
      - name: Deploy __video-maker-lambda To AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: video-maker
          zip_file: __video-maker-lambda.zip
